name: Build LaTeX document
on:
  - pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: paper.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: paper
